language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
services:
    - mysql
    - redis-server
before_script:
  - mysql -e 'create database `goteo-test`;'
  - mysql < goteoapi/tests/sql/schema_mysql.sql
  - mysql < goteoapi/tests/sql/data_mysql.sql
install:
    - pip install -r requirements.txt
    - pip install -r goteoapi_*/requirements.txt
env:
    - GOTEO_API_CONFIG_FILE=$(realpath config_test.py.dist)
script: nosetests
