FootPrint API
This resource returns social commitments information.
"http://developers.goteo.org/doc/footprints"
---
tags:
    - footprints

security:
    - basic: []

definitions:
    - schema:
        id: FootPrint
        properties:
            id:
                type: string
                description: FootPrint unique identifier
            name:
                type: string
                description: FootPrint name
            description:
                type: string
                description: FootPrint short description
            icon-url:
                type: string
                description: URL for the image resource associated with this social commitment
            total-users:
                type: integer
                description: Number of users interested in the FootPrint
            total-projects:
                type: integer
                description: Number of published projects in the FootPrint

    - schema:
        id: MetaFootPrint
        properties:
            total:
                type: integer
                description: Total elements available for the collection
            node:
                type: array
                description: Only if filtering by node
                items:
                    type: string
            project:
                type: array
                items:
                    type: string
                description: Only if filtering by project
            lang:
                type: array
                items:
                    type: string
                description: Only if filtering by lang
            from_date:
                type: string
                description: Only if filtering by from_date
            to_date:
                type: string
                description: Only if filtering by to_date
            location:
                type: array
                items:
                    type: number
                description: Only if filtering by location


    - schema:
        id: ResponseFootPrint
        properties:
            items:
                type: array
                items:
                    $ref: '#/definitions/api_footprints_footprints_get_FootPrint'
            meta:
                $ref: '#/definitions/api_footprints_footprints_get_MetaFootPrint'

parameters:
    - in: query
      type: string
      name: node
      description: Filter by individual node(s). Multiple nodes can be specified. Restricts the list to the footprints used in projects assigned in that nodes
      collectionFormat: multi
    - in: query
      type: string
      name: call
      description: Filter by individual matchfunding call(s). Multiple calls can be specified. Restricts the list to the projects originally created in that call(s)
      collectionFormat: multi
    - in: query
      name: project
      description: Filter by individual project(s). Multiple projects can be specified. Restricts the list to the footprints used in that projects
      type: string
      collectionFormat: multi
    - in: query
      name: from_date
      description: Filter from date. Ex. "2013-01-01". Restricts the list to the footprints used in projects created between that dates
      type: string
      format: date
    - in: query
      name: to_date
      description: Filter until date.. Ex. "2014-01-01". Restricts the list to the footprints used in projects created between that dates
      type: string
      format: date
    - in: query
      name: category
      description: Filter by category. Multiple categories can be specified. Restricts the list to the social commitments matching with that category(ies)
      type: integer
    - in: query
      name: social_commitment
      description: Filter by social commitment. Multiple social commitments can be specified. Restricts the list to the social commitments specified
      type: integer
      collectionFormat: multi
    - in: query
      name: lang
      description: Get results by specified lang. Multiple langs can be specified
      type: string
      collectionFormat: multi
    - in: query
      name: location
      description: Filter by project location (Latitude,longitude,Radius in Km). Restricts the list to the footprints used in projects geolocated in that area
      type: number
      collectionFormat: csv
    # - in: query
    #   name: page
    #   description: Page number (starting at 1) if the result can be paginated
    #   type: integer
    # - in: query
    #   name: limit
    #   description: Page limit (maximum 50 results, defaults to 10) if the result can be paginated
    #   type: integer

responses:
    200:
        description: List of available footprints
        schema:
            $ref: '#/definitions/api_footprints_footprints_get_ResponseFootPrint'
    401:
        description: Resource requires authorization
    400:
        description: Invalid parameters format
