License API
This resource returns license information.
http://developers.goteo.org/doc/licenses
---
tags:
    - licenses

security:
    - basic: []

definitions:
    - schema:
        id: License
        properties:
            id:
                type: string
                description: License unique identifier
            name:
                type: string
                description: License name
            description:
                type: string
                description: License description
            url:
                type: string
                description: URL where to find the license content terms
            svg-url:
                type: string
                description: URL with the SVG logo of the license
            total-rewards:
                type: integer
                description: Number of published projects using the license in some of its rewards
            total-projects:
                type: integer
                description: Number of rewards using the license for all published projects
parameters:
    - in: query
      type: string
      name: node
      description: Filter by individual node(s). Multiple nodes can be specified. Restricts the list to the licenses used in project rewards where the project is assigned in that nodes
      collectionFormat: multi
    - in: query
      name: project
      description: Filter by individual project(s). Multiple projects can be specified. Restricts the list to the licenses used in rewards for that projects
      type: string
      collectionFormat: multi
    - in: query
      name: lang
      description: Get results by specified lang. Multiple langs can be specified
      type: string
      collectionFormat: multi
    - in: query
      name: from_date
      description: Filter from date. Ex. "2013-01-01". Restricts the list to the licenses used in the project rewards where the project was published after that date (included)
      type: string
      format: date
    - in: query
      name: to_date
      description: Filter until date.. Ex. "2014-01-01". Restricts the list to the licenses used in the project rewards where the project was published before that date (included)
      type: string
      format: date
    - in: query
      name: category
      description: Filter by project category. Multiple categories can be specified. Restricts the list to the licenses used in project rewards in that categories
      type: integer
    - in: query
      name: lang
      description: Get results by specified lang. Multiple langs can be specified
      type: string
      collectionFormat: multi
    - in: query
      name: location
      description: Filter by project location (Latitude,longitude,Radius in Km). Restricts the list to the licenses used in project rewards where the project is geolocated in that area.
      type: number
      collectionFormat: csv
    # - in: query
    #   name: page
    #   description: Page number (starting at 1) if the result can be paginated
    #   type: integer
    # - in: query
    #   name: limit
    #   description: Page limit (maximum 50 results, defaults to 10) if the result can be paginated
    #   type: integer
responses:
    200:
        description: List of available licenses
        schema:
            type: array
            id: licenses
            items:
                $ref: '#/definitions/api_licenses_licenses_get_License'
    401:
        description: Resource requires authorization
    400:
        description: Invalid parameters format
