License API
This resource returns license information.
<a href="http://developers.goteo.org/doc/licenses">developers.goteo.org/doc/licenses</a>
---
tags:
    - licenses

security:
    - basic: []

definitions:
    - schema:
        id: License
        properties:
            id:
                type: string
                description: License unique identifier
            name:
                type: string
                description: License name
            description:
                type: string
                description: License short description
            url:
                type: string
                description: License's URL
            svg-url:
                type: string
                description: Icon URL for the license
            total-rewards:
                type: integer
                description: Number of rewards using this license
            total-projects:
                type: integer
                description: Number of projects using this license
parameters:
    - in: query
      type: string
      name: node
      description: Filter by individual node(s). Multiple nodes can be specified. Restricts the list to the licenses used in projects assigned in that nodes
      collectionFormat: multi
    - in: query
      name: project
      description: Filter by individual project(s). Multiple projects can be specified. Restricts the list to the licenses used in that projects
      type: string
      collectionFormat: multi
    - in: query
      name: from_date
      description: Filter from date. Ex. "2013-01-01". Restricts the list to the licenses used in projects created between that dates
      type: string
      format: date
    - in: query
      name: to_date
      description: Filter until date.. Ex. "2014-01-01". Restricts the list to the licenses used in projects created between that dates
      type: string
      format: date
    # - in: query
    #   name: category
    #   description: Filter by project category. Multiple licenses can be specified. Restricts the list to the licenses used in projects in that licenses
    #   type: integer
    - in: query
      name: lang
      description: Get results by specified lang. Multiple langs can be specified
      type: string
      collectionFormat: multi
    - in: query
      name: location
      description: Filter by project location (Latitude,longitude,Radius in Km). Restricts the list to the licenses used in projects geolocated in that area
      type: number
      collectionFormat: csv
    # - in: query
    #   name: page
    #   description: Page number (starting at 1) if the result can be paginated
    #   type: integer
    # - in: query
    #   name: limit
    #   description: Page limit (maximum 50 results, defaults to 10) if the result can be paginated
    #   type: integer
responses:
    200:
        description: List of available licenses
        schema:
            type: array
            id: licenses
            items:
                $ref: '#/definitions/api_licenses_licenses_get_License'
    400:
        description: Invalid parameters format
    # 404:
    #     description: Resource not found
