License API
This resource returns license information.
http://developers.goteo.org/doc/licenses
---
tags:
    - licenses

security:
    - basic: []

definitions:
    - schema:
        id: License
        properties:
            id:
                type: string
                description: License unique identifier
            name:
                type: string
                description: License name
            description:
                type: string
                description: License description
            url:
                type: string
                description: URL where to find the license content terms
            svg-url:
                type: string
                description: URL with the SVG logo of the license
            total-rewards:
                type: integer
                description: Number of published projects using the license in some of its rewards
            total-projects:
                type: integer
                description: Number of rewards using the license for all published projects

    - schema:
        id: MetaLicense
        properties:
            total:
                type: integer
                description: Total elements available for the collection
            node:
                type: array
                description: Only if filtering by node
                items:
                    type: string
            project:
                type: array
                items:
                    type: string
                description: Only if filtering by project
            lang:
                type: array
                items:
                    type: string
                description: Only if filtering by lang
            from_date:
                type: string
                description: Only if filtering by from_date
            to_date:
                type: string
                description: Only if filtering by to_date
            category:
                type: array
                items:
                    type: number
                description: Only if filtering by category
            location:
                type: array
                items:
                    type: number
                description: Only if filtering by location

    - schema:
        id: ResponseLicense
        properties:
            items:
                type: array
                items:
                    $ref: '#/definitions/api_licenses_licenses_get_License'
            meta:
                $ref: '#/definitions/api_licenses_licenses_get_MetaLicense'

parameters:
    - in: query
      type: string
      name: node
      description: Filter by individual node(s). Multiple nodes can be specified. Restricts the list to the licenses used in project rewards where the project is assigned in that nodes
      collectionFormat: multi
    - in: query
      type: string
      name: call
      description: Filter by individual matchfunding call(s). Multiple calls can be specified. Restricts the list to the projects originally created in that call(s)
      collectionFormat: multi
    - in: query
      name: project
      description: Filter by individual project(s). Multiple projects can be specified. Restricts the list to the licenses used in rewards for that projects
      type: string
      collectionFormat: multi
    - in: query
      name: lang
      description: Get results by specified lang. Multiple langs can be specified
      type: string
      collectionFormat: multi
    - in: query
      name: from_date
      description: Filter from date. Ex. "2013-01-01". Restricts the list to the licenses used in the project rewards where the project was published after that date (included)
      type: string
      format: date
    - in: query
      name: to_date
      description: Filter until date.. Ex. "2014-01-01". Restricts the list to the licenses used in the project rewards where the project was published before that date (included)
      type: string
      format: date
    - in: query
      name: category
      description: Filter by project category. Multiple categories can be specified. Restricts the list to the licenses used in rewards of projects with that category(ies)
      type: integer
      collectionFormat: multi
  - in: query
      name: social_commitment
      description: Filter by project social commitment. Multiple social commitments can be specified. Restricts the list to the licenses used in rewards of projects with that social commitment(s)
      type: integer
      collectionFormat: multi
    - in: query
      name: location
      description: Filter by project location (Latitude,longitude,Radius in Km). Restricts the list to the licenses used in project rewards where the project is geolocated in that area.
      type: number
      collectionFormat: csv
    # - in: query
    #   name: page
    #   description: Page number (starting at 1) if the result can be paginated
    #   type: integer
    # - in: query
    #   name: limit
    #   description: Page limit (maximum 50 results, defaults to 10) if the result can be paginated
    #   type: integer
responses:
    200:
        description: List of available licenses
        schema:
            $ref: '#/definitions/api_licenses_licenses_get_ResponseLicense'
    401:
        description: Resource requires authorization
    400:
        description: Invalid parameters format
